Adding a warning when the values are more than 1000
webrtc/samples pull request #1018
Opened 2018-02-16 14:18 UTC by vkkkumar

**Description**
Adding a warning when the values are more than 1000

**Purpose**
This is an improvement to the existing samples page. When a user enters a very large value it can misguide that the progress is not happening. By adding this note it informs the user to wait patiently or try with a smaller value. 

#974

2018-03-08 12:08 UTC, KaptenJansson requested changes

2018-03-08 12:08 UTC, KaptenJansson commented on src/content/datachannel/datatransfer/js/main.js
> +        errorMessage.innerHTML = '<p>Progress can be slow when the values are greater than 1000.</p>';
Indentation should match the above `if` statement. Also this is not really an error, its a warning and should be displayed as such.

2018-03-26 11:48 UTC, KaptenJansson commented
Ping

2018-07-23 07:55 UTC, ErikHellman commented
This PR is replaced by https://github.com/webrtc/samples/pull/1079

2018-07-23 07:55 UTC, closed without merging