Add github ribbon to all pages
webrtc/samples pull request #1122
Opened 2018-09-11 12:00 UTC by ErikHellman

Let's add the github ribbon to all samples for easier access to the sources.

2018-09-11 15:29 UTC, samdutton commented on src/content/datachannel/basic/index.html
> +        style="position: absolute; top: 0; left: 0; border: 0;"
Would be great to move this out of the HTML.

2018-09-11 15:30 UTC, samdutton approved these changes
LGTM apart from request to move CSS out of HTML.

2018-10-16 15:24 UTC, KaptenJansson requested changes
LGTM overall but agree on not including CSS in HTML.

2018-10-17 08:21 UTC, ErikHellman commented
I'm closing this and will open a new PR later on.

2018-10-17 08:21 UTC, closed without merging