bandwidth: Use RTCRtpSender.setParameters in Firefox 64 and up
webrtc/samples pull request #1128
Opened 2018-09-20 13:16 UTC by Pehrsons

Firefox [bug 1253499](https://bugzilla.mozilla.org/show_bug.cgi?id=1253499) has fixed calling setParameters during a call.

2018-09-20 13:34 UTC, jan-ivar commented
@KaptenJansson @alvestrand 

Hi, @Pehrsons works for Mozilla. I forget, how does he get on the Mozilla CLA, do you remember?

2018-10-16 15:23 UTC, KaptenJansson commented
He needs to use an email address that belongs to the company group I believe.

2018-10-16 15:27 UTC, KaptenJansson requested changes
LGTM after CLA is signed.

2018-10-24 16:15 UTC, Pehrsons commented
Finally got on the CLA list, and rebased. Thanks!

2018-10-31 14:17 UTC, Pehrsons commented
ping @KaptenJansson

2018-11-01 05:20 UTC, KaptenJansson approved these changes

2018-11-01 05:31 UTC, merged