Add new sample for video processing with insertable streams
webrtc/samples pull request #1378
Opened 2020-11-16 22:13 UTC by dogben

First draft, including the following UI options:

- MediaStream source selection:
  * Camera
  * Video
  * Peer connection (from camera)
- Optionally include the source video in the page
- Transform selection:
  * WebGL
  * Canvas2D
  * Drop frames at random
  * Delay all frames by 100ms
- Transformed stream destination selection:
  * Video
  * Peer connection (to video)

Includes a link to the [explainer](https://github.com/w3c/mediacapture-insertable-streams) and a note regarding the experimental nature of the API and how to enable it.

2020-11-17 12:41 UTC, KaptenJansson requested changes
Made some comments inline but one general remark, the main.js file is over 1200 lines, maybe split it up? I know it's just a demo/sample page but that file is a bit daunting and I think splitting it up into logical pieces would make sense here. Maybe split into libraries and an interface/api file? @alvestrand WDYT?

2020-11-17 12:41 UTC, KaptenJansson commented on src/content/insertable-streams/video/css/main.css
> + *  Copyright (c) 2015 The WebRTC project authors. All Rights Reserved.
Current copyright year for new files.

2020-11-17 12:41 UTC, KaptenJansson commented on src/content/insertable-streams/video/index.html
> + *  Copyright (c) 2015 The WebRTC project authors. All Rights Reserved.
Current copyright year for new files.

2020-11-17 12:41 UTC, KaptenJansson commented on src/content/insertable-streams/video/index.html
> +    <!--video id="sourceVideo" playsinline autoplay muted></video-->
Remove commented out code.

2020-11-17 12:41 UTC, KaptenJansson commented on src/content/insertable-streams/video/js/main.js
> + *  Copyright (c) 2015 The WebRTC project authors. All Rights Reserved.
Current copyright year for new files.

2020-11-17 12:41 UTC, KaptenJansson commented on src/content/insertable-streams/video/js/main.js
> + * Assebles a MediaStreamSource, FrameTransform, and MediaStreamSink together.
Assemble

2020-11-17 14:21 UTC, dogben commented
> ... the main.js file is over 1200 lines, maybe split it up? ...

Done. If there's a better way to include definitions across files for this repo, let me know.

2020-11-18 14:48 UTC, KaptenJansson approved these changes
LGTM with nits. Really impressive!

2020-11-18 14:48 UTC, KaptenJansson commented on src/content/insertable-streams/video/js/main.js
> + * captureStream on HTMLMediaElement or HTMLCanvasElement.
Match indentation above.

2020-11-18 14:48 UTC, KaptenJansson commented on src/content/insertable-streams/video/js/main.js
> +  // pipeline?.getSource()?.setVisibility(sourceVisibleCheckbox.checked);
Remove?

2020-11-18 15:38 UTC, merged