Add Plan B mode to negotiation-timing page
webrtc/samples pull request #1426
Opened 2021-02-18 13:07 UTC by henbos

This PR adds a "Start (legacy)" button that runs Plan B, and renames the old start-button to "Start (standard)".

Because transceivers are not available in Plan B, addTrack() is used instead of addTransceiver(). And because of Plan B limitations, the track has to actually exist at SDP offer time, so we can't replace(null) the dummy track immediately - we have to wait until after negotiation to do so.

2021-02-18 13:15 UTC, henbos commented
Please take a look @alvestrand

2021-02-18 13:29 UTC, alvestrand approved these changes
Looks good. If you fix the format issues to make the linter happy, and move the audio impairment measurement ahead of the cleanup code, I think we should just merge.

2021-02-18 13:29 UTC, alvestrand commented on src/content/peerconnection/negotiate-timing/js/main.js
>    result.audioImpairment = await measureAudioImpairment(pc2);
can you move the measurement before the clone cleanup, so that we don't get hit by any audio impact from that part?

2021-02-18 13:29 UTC, alvestrand commented on src/content/peerconnection/negotiate-timing/js/main.js
> +  startButtonPlanB.disabled = true;
hm. this is ugly (when we have start buttons, code referring to them should go with the button-specific thing), but startButton and startButtonPlanB have to know about each other, so perhaps this is the best way to write it. No change needed.

2021-02-18 14:51 UTC, fippo commented
I thought we had an agreement to not do non-standard stuff in the samples anymore? You might want to use https://github.com/webrtc/test-pages for such things

2021-02-18 15:02 UTC, henbos commented
> I thought we had an agreement to not do non-standard stuff in the samples anymore?

The samples pages should definitely not use Plan B as an example of "how to do things". I made an exception this time because this page is a demo for measuring the performance and audio glitches and has been very useful to debug performance issues. The UI displays it as "Start (legacy)" so I hope it is not seen as an encouragement on how to write an application.

2021-02-18 15:02 UTC, henbos commented
I'll remove it in a couple of chrome releases.

2021-02-18 16:59 UTC, jan-ivar commented
I agree with @fippo here this sends the wrong message. I don't think the word "legacy" is strong enough to counter the impression this was ever a standard.

> ...very useful to debug performance issues

It should be able to serve this same purpose in a personal github.com repo.

2021-02-18 17:00 UTC, jan-ivar requested changes
Would rather we not merge this.

2021-02-18 17:09 UTC, hthetiot commented
> I'll remove it in a couple of chrome releases.

Can you share a timeline for removing PlanB support. Thx.

2021-02-18 18:26 UTC, henbos commented
> Would rather we not merge this.

Ok. Even if we add big red letters saying that this legacy code path will be deleted in August and only exists for temporary debugging purposes?

2021-02-18 21:25 UTC, fippo commented
@henbos past promises by googlers or google contractors that were broken left a bad impression. I still think the other repo is the way to go, @KaptenJansson will be happy to help :-)

2021-02-18 23:51 UTC, jan-ivar commented
> Can you share a timeline for removing PlanB support. Thx.

![image](https://user-images.githubusercontent.com/3136226/108436897-4b1f7100-721a-11eb-8b9d-6bfe5dbcf3af.png)

2021-02-19 08:08 UTC, henbos commented
I agree that we shouldn't spread Plan B usage on sample pages in general. The reason why I thought it would have been acceptable to add Plan B to this particular page was that...
- The debugging I was going to do on Plan B vs Unified Plan was in the name of removing Plan B from Chromium. Our efforts into optimizing negotiation by profiling both SDP semantics have led to pinpointing issues that we have resolved with substantial improvements in M88-M90. This has been especially good news for Unified Plan.
- This is not a sample page for "how to do things", it is just a performance measurement tool.
- Plan B now triggers a deprecation warning and we have a target removal milestone (M93), lessening the risk that people think Plan B is OK after seeing it on a page like this.

But there seems to be a rough consensus against this PR, so I'll move it to my personal repo.

2021-02-19 08:08 UTC, closed without merging

2021-02-19 18:23 UTC, hthetiot commented
> > Can you share a timeline for removing PlanB support. Thx.
> 
> ![image](https://user-images.githubusercontent.com/3136226/108436897-4b1f7100-721a-11eb-8b9d-6bfe5dbcf3af.png)

Thx @jan-ivar 
I have not seen that yet, is that on chrome stable or canary only for now?

2021-02-19 23:15 UTC, jan-ivar commented
> I have not seen that yet, is that on chrome stable or canary only for now?

@hthetiot It was added in M89. See [release notes](https://groups.google.com/g/discuss-webrtc/c/Zrsn2hi8FV0/m/KIbn0EZPBQAJ). Type the following into web console to see it:
```js
new RTCPeerConnection({sdpSemantics: "plan-b"})
```