munge-sdp: make it work in Safari
webrtc/samples pull request #908
Opened 2017-06-13 04:59 UTC by fippo

Safaris RTCSessionDescritpion.sdp is read-only as specified
    http://w3c.github.io/webrtc-pc/#rtcsessiondescription-class
Adapts the munge-sdp demo to deal with this.

2017-06-14 08:18 UTC, KaptenJansson requested changes

2017-06-14 08:18 UTC, KaptenJansson commented on src/content/peerconnection/pc1/index.html
> +  <script src="../../../js/adapter.js"></script>
How does this work? We no longer use the npm webrtc-adapter package in samples?

2017-06-14 08:22 UTC, fippo commented on src/content/peerconnection/pc1/index.html
> +  <script src="../../../js/adapter.js"></script>
ups... I just noticed as well. Squashing...

2017-06-14 08:24 UTC, KaptenJansson approved these changes

2017-06-14 08:26 UTC, KaptenJansson commented
LGTM

2017-06-15 06:52 UTC, KaptenJansson commented
Merging with the same reason as #906.

2017-06-15 06:53 UTC, merged