webrtc-adapter version selector
webrtc/samples pull request #952
Opened 2017-11-16 22:24 UTC by CezaryDanielNowak

This code is meant to help debugging regressions in adapter-webrtc.
User is able to select any version of the script available in cdnjs

2017-11-16 22:26 UTC, CezaryDanielNowak commented
I signed it!

2017-12-08 10:31 UTC, KaptenJansson commented
Have no idea why travis is not working for this PR

2017-12-08 10:36 UTC, KaptenJansson requested changes

2017-12-08 10:36 UTC, KaptenJansson commented on src/js/adapter-loader.js
> +    ? 'https://cdnjs.cloudflare.com/ajax/libs/webrtc-adapter/' + localStorage.alternativeAdapterVersion + '/adapter.min.js'
Could you try to send a new commit and see if it triggers travis? You start by changing all the lines to be max 80 chars long (the travis ci will complain about this anyway when it actually runs).

2017-12-08 11:34 UTC, fippo commented
i'd do this without the UI. For dev purposes its ok to manipulate localStorage. Other than that this seems like a good idea

2018-01-30 13:33 UTC, KaptenJansson commented
Ping

2018-02-01 10:05 UTC, KaptenJansson commented
Pong

2018-03-08 11:58 UTC, KaptenJansson commented
Closing due to age.

2018-03-08 11:58 UTC, closed without merging