Enable testing 4K in the test page (issue 963)
webrtc/samples pull request #965
Opened 2017-12-04 15:04 UTC by rantonysamy

**Description**
Adding 4k button in the testing page to test 4k camera and its resolution. 

**Purpose**
4096x2160 (4K) has to be added in the page https://webrtc.github.io/samples/src/content/getusermedia/resolution/ 

Added button 4k and all the related code to bring this button to test the resolution.

2017-12-04 15:11 UTC, KaptenJansson requested changes

2017-12-04 15:11 UTC, KaptenJansson commented on src/content/getusermedia/resolution/js/main.js
> +var 4kButton = document.querySelector('#4k');
Variables cannot start with numbers.

2017-12-04 15:11 UTC, KaptenJansson commented
Also I merged the branch with master, you might have to do a git pull before making changes.

2017-12-04 15:15 UTC, KaptenJansson commented on src/content/getusermedia/resolution/js/main.js
> +var 4kButton = document.querySelector('#4k');
And that's why it red in the github editor as well.

2017-12-04 15:30 UTC, rantonysamy commented
Yes, since you merged it with the master, I took that commit "fe45a6eebbbe2bf79f7a" as a base commit and reset my git branch with that, and sent a fixup.

2017-12-04 15:45 UTC, KaptenJansson commented on src/content/getusermedia/resolution/js/test.js
> +test('Four K capture', function(t) {
Here you can have "4K" since it's in a string.

2017-12-04 15:45 UTC, KaptenJansson commented on src/content/getusermedia/resolution/js/test.js
> +test('Four K capture', function(t) {
But I think either 4K is not enabled on Chrome or the fake camera capture device does not support 4K hence the test times out. I think you can comment out this test and add a comment saying that the fake camera capture device does not support 4K.

You could try this out locally and see if 4K works with a 4K camera at all by modifying the values for the Full HD button on https://webrtc.github.io/samples/src/content/getusermedia/resolution/ in the browser before you click the full HD button. If that works, then try the same using the fake camera ( start Chrome with the command line flag: --use-fake-device-for-media-stream).

2017-12-05 13:50 UTC, KaptenJansson approved these changes

2017-12-05 13:50 UTC, merged