Add a new demo showing old and new stats on a PeerConnection.
webrtc/samples pull request #994
Opened 2018-01-16 15:40 UTC by alvestrand

Mostly useful when trying to figure out "what's the format of
that particular stat in (old/new) in this version".

Not really pretty enough to publish in its present form.

2018-01-30 13:45 UTC, KaptenJansson requested changes
Just some quick comments.

2018-01-30 13:45 UTC, KaptenJansson commented on src/content/peerconnection/old-new-stats/css/main.css
> + *  Copyright (c) 2015 The WebRTC project authors. All Rights Reserved.
Update copyright throughout since these are a new files.

2018-01-30 13:45 UTC, KaptenJansson commented on src/content/peerconnection/old-new-stats/js/main.js
> +main();
Maybe let onload() execute this?

2018-01-30 13:45 UTC, KaptenJansson commented on src/content/peerconnection/old-new-stats/js/main.js
> +  console.log(JSON.stringify(results));
I think trace() can handle objects since a while back.

2018-03-08 11:59 UTC, KaptenJansson commented
Any cycles to finish this?

2018-03-26 11:49 UTC, KaptenJansson commented
Ping

2018-06-15 15:54 UTC, henbos commented
googlebot saddest bot. Should this PR be resubmitted so that it is "owned" by you?

2018-06-15 16:12 UTC, henbos requested changes

2018-06-15 16:12 UTC, henbos commented on .gitignore
> +.idea
?

2018-06-15 16:12 UTC, henbos commented on .github/ISSUE_TEMPLATE.md
> +# Please read first!
Not sure why this shows up here?

2018-06-15 16:12 UTC, henbos commented on src/content/datachannel/filetransfer/js/main.js
> +      remoteConnection.getStats().then(function(stats) {
It looks like this PR is doing a lot of different things, can you split it up into multiple PRs for easier reviewability (for example one PR per sample)? If it has to be reverted it's not an all-or-nothing thing and can more easily be re-landed too.

2018-06-15 17:57 UTC, samdutton commented on .github/ISSUE_TEMPLATE.md
> +**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**
I'd put this *before* the checkboxes: 

> Please make sure to provide the following:
> 
> [ ] Steps to reproduce
> [ ] Browser name and version
> [ ] Link to sample here, or a modified version
> 
> The issue will be closed if any of these are missing.

2018-06-15 17:58 UTC, samdutton commented on index.html
> +      <p>Some of the samples use new browser features. They may only work in <a href="https://www.google.com/chrome/browser/canary.html" title="Download Chrome Canary">Chrome Canary</a>, <a href="htt
> High Sierra

What about iOS?

2018-06-15 18:00 UTC, samdutton commented on index.html
> +      <p>Some of the samples use new browser features. They may only work in <a href="https://www.google.com/chrome/browser/canary.html" title="Download Chrome Canary">Chrome Canary</a>, <a href="htt
Should refer to Safari Tech Preview (https://developer.apple.com/safari/technology-preview) and Microsoft Edge Preview (https://insider.windows.com).

2018-06-15 18:01 UTC, samdutton commented on src/content/datachannel/filetransfer/js/main.js
> +          var bytesNow = activeCandidatePair.bytesReceived;
Use `const` or `let`.

2018-06-15 18:05 UTC, samdutton commented on src/content/devices/multi/index.html
> +    <p>This demo must be run from localhost or over HTTPS Chrome 49 or later, Firefox is not supported yet.</p>
All the WebRTC demos need to be run from localhost, HTTPS or a `file://` URL. Maybe add a note at the top?

I would remove stuff like 'Chrome 49 or later'. This is no longer relevant.

2018-06-15 18:06 UTC, samdutton commented on src/content/getusermedia/resolution/js/main.js
> +eightKButton.onclick = function() {
Stuff like this could use fat arrow syntax:

`eightKButton.onclick = () => {...}`

2018-06-15 18:15 UTC, samdutton commented on src/content/peerconnection/old-new-stats/js/main.js
> +/*
There's quite a lot of stuff here that doesn't follow Google JavaScript style and will cause linting errors: semi-colons at the end of every line, spacing around function names, etc. 

I think you should run all the files through ESLint (using [.eslintrc](https://github.com/webrtc/samples/blob/gh-pages/.eslintrc)) and fix accordingly.

Same for CSSLint if necessary.

2018-06-15 18:17 UTC, samdutton commented on src/content/peerconnection/pr-answer/js/main.js
>  var vid1 = document.getElementById('vid1');
As with other files, `const` and `let` throughout.

2018-06-16 14:04 UTC, ErikHellman commented on .gitignore
> +.idea
I use WebStorm, since it lets me do proper refactoring. It leaves a .idea project folder that I don't want added to the repo.

2018-06-16 14:05 UTC, ErikHellman commented
Will fix your comments once I'm back from vacation. Agree with all of it! :)

2018-07-23 09:01 UTC, ErikHellman commented
Ping @henbos and @samdutton 

I fixed the review comments and made some other improvements.

2018-07-23 09:46 UTC, samdutton commented
LGTM, though I think it would be worth adding a sentence to explain what 'old' and 'new' mean for this sample.

One other suggestion — not crucial, but these samples should probably use template literals throughout. 

For example this:

```
remoteVideoStatsDiv.innerHTML = `<strong>Video dimensions:</strong> ${remoteVideo.videoWidth}x${remoteVideo.videoHeight}px`;
```
Rather than this:
```
remoteVideoStatsDiv.innerHTML = '<strong>Video dimensions:</strong> ' + remoteVideo.videoWidth + 'x' + remoteVideo.videoHeight + 'px';
```

2018-07-23 10:30 UTC, merged

2018-07-23 10:34 UTC, fippo commented
https://github.com/cpojer/js-codemod#template-literals helps with using templates